language: node_js
node_js:
  - "0.10"

env:
  global:
    - TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"
    - GIT_USER=webanimbot
    - GIT_EMAIL=webanimbot@gmail.com

install:
  - ./build/install-bikeshed.sh
  - npm install

script:
  - ./build/travis.sh
