language: node_js
node_js:
  - "0.10"

env:
  global:
    - TRAVIS_COMMIT_MSG="$(git log --format=%B --no-merges -n 1)"

install:
  - ./build/setup-bikeshed.sh
  - npm install

script:
  - grunt build
